name: Build and deploy Node.js app to Azure Web App - priyankadget

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies for Node.js app (Strapi)
      working-directory: ./api
      run: |
        npm i

    - name: Deploy Node.js app to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'priyankadget'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE0F9B149CED42D884D82F56B4FD15F9 }}
        package: ./api

    - name: Install dependencies for Next.js app
      working-directory: ./ui
      run: |
        npm i

    - name: Build and export Next.js app
      working-directory: ./ui
      run: |
        npm next build
        npm next start

    - name: Deploy Next.js app to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'priyankadget'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE0F9B149CED42D884D82F56B4FD15F9 }}
        package: ./ui
