# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - priyankadget

on:
  push:
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test strapi
        working-directory: ./api
        run: |
          npm install
          npm run build --if-present
      
      - name: Archive files strapi
        run: tar -czvf strapi-build.tar.gz ./api
          
      - name: Upload artifact for deployment job strapi
        uses: actions/upload-artifact@v2
        with:
          name: strapi-app
          path: strapi-build.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-strapi.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job strapi
        uses: actions/download-artifact@v2
        with:
          name: strapi-app
      
      - name: Extract artifact strapi
        run: tar -xzvf strapi-build.tar.gz -C .

      - name: 'Deploy to Azure Web App - Strapi'
        id: deploy-to-webapp-strapi
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'priyankadget-api'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B8573C8142C14E3CBBE4464F6975B414 }}
          package: api
