# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - priyankadget

on:
  push:
    branches:
      - main
  workflow_dispatch:
      -trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies for strapi app
        working-directory: site/wwwroot/api
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload artifact for deployment job
        working-directory: site/wwwroot/api
        uses: actions/upload-artifact@v2
        with:
          name: strapi-app
          path: site/wwwroot/api

      - name: Install dependencies for Next.js app
        working-directory: site/wwwroot/ui
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Upload artifact for deployment job
        working-directory: site/wwwroot/ui
        uses: actions/upload-artifact@v2
        with:
          name: next-app
          path: site/wwwroot/ui

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: strapi-app
      
      - name: Build and export strapi app
      working-directory: site/wwwroot/strapi
      run: |
        npm run develop

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'priyankadget'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE0F9B149CED42D884D82F56B4FD15F9 }}
          package: site/wwwroot/api

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: next-app
      
      - name: Build and export Next.js app
      working-directory: site/wwwroot/ui
      run: |
        npm run start

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'priyankadget'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE0F9B149CED42D884D82F56B4FD15F9 }}
          package: site/wwwroot/ui
