name: Deploy Strapi App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x' 

    - name: Build Strapi App
      run: |
        npm ci
        npm run build
      working-directory: ./api

    - name: Publish Strapi App
      uses: azure/webapps-deploy@v2
      with:
        package: /home/site/wwwroot/api/dist/build
        app-name: priyankadget
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1 }}
        additional-args: -d C:\home\site\wwwroot\api